[project]
name = "olist-customer-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.6",
    "pandas>=3.0.6",
    "ruff>=0.16.10",
]
[project.scripts]
ingest = "ingestion.load_data:main"
[tool.uv]
package = true
